// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package DI

// Injectors from wire.go:

func InitLevel2(msg string) *level2 {
	diLevel0 := newLevel0(msg)
	diLevel1 := newLevel1(diLevel0)
	diLevel2 := newLevel2(diLevel1, diLevel0)
	return diLevel2
}
